In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/conditions_en.csv")

In [4]:
df.head()

       address                              Address
0        clear  clear conditions throughout the day
1   clearingpm            clearing in the afternoon
2   cloudcover                          Cloud Cover
3   cloudierpm     becoming cloudy in the afternoon
4  coolingdown                         cooling down

In [5]:
conditions = df[df['address'].str.contains("type")]

In [6]:
conditions.head()

    address                               Address
75   type_1              Blowing Or Drifting Snow
76  type_10  Heavy Freezing Drizzle/Freezing Rain
77  type_11  Light Freezing Drizzle/Freezing Rain
78  type_12                          Freezing Fog
79  type_13                   Heavy Freezing Rain

In [7]:
conditions.to_json("./data/conditions_en.json", index=False)

In [8]:
import json

In [9]:
conditions_dict = {}

In [20]:
codes = conditions["address"].to_numpy()
desc = conditions["Address"].to_numpy()

In [21]:
for i in range(len(codes)):
    conditions_dict[codes[i]] = desc[i]

In [22]:
conditions_dict

{'type_1': 'Blowing Or Drifting Snow',
 'type_10': 'Clear',
 'type_11': 'Diamond Dust',
 'type_12': 'Drizzle',
 'type_13': 'Dust storm',
 'type_14': 'Fog',
 'type_15': 'Freezing Drizzle/Freezing Rain',
 'type_16': 'Freezing Fog',
 'type_17': 'Funnel Cloud/Tornado',
 'type_18': 'Hail',
 'type_19': 'Hail Showers',
 'type_2': 'Heavy Drizzle',
 'type_20': 'Heavy Drizzle/Rain',
 'type_21': 'Heavy Freezing Drizzle/Freezing Rain',
 'type_22': 'Heavy Freezing Rain',
 'type_23': 'Heavy Rain',
 'type_24': 'Heavy Rain And Snow',
 'type_25': 'Heavy Snow',
 'type_26': 'Ice',
 'type_27': 'Light Drizzle',
 'type_28': 'Light Drizzle/Rain',
 'type_29': 'Light Freezing Drizzle/Freezing Rain',
 'type_3': 'Light Freezing Rain',
 'type_30': 'Light Rain',
 'type_31': 'Light Rain And Snow',
 'type_32': 'Light Snow',
 'type_33': 'Lightning Without Thunder',
 'type_34': 'Mist',
 'type_35': 'Overcast',
 'type_36': 'Partially cloudy',
 'type_37': 'Precipitation In Vicinity',
 'type_38': 'Rain',
 'type_39': 'Rain Showers',
 'type_4': 'Sky Coverage Decreasing',
 'type_40': 'Sky Coverage Increasing',
 'type_41': 'Sky Unchanged',
 'type_42': 'Smoke Or Haze',
 'type_43': 'Snow',
 'type_5': 'Snow And Rain Showers',
 'type_6': 'Snow Showers',
 'type_7': 'Squalls',
 'type_8': 'Thunderstorm',
 'type_9': 'Thunderstorm Without Precipitation'}

In [25]:
conditions_json = json.dumps(conditions_dict)

In [36]:
conditions_json

'{"type_1": "Blowing Or Drifting Snow", "type_10": "Clear", "type_11": "Diamond Dust", "type_12": "Drizzle", "type_13": "Dust storm", "type_14": "Fog", "type_15": "Freezing Drizzle/Freezing Rain", "type_16": "Freezing Fog", "type_17": "Funnel Cloud/Tornado", "type_18": "Hail", "type_19": "Hail Showers", "type_2": "Heavy Drizzle", "type_20": "Heavy Drizzle/Rain", "type_21": "Heavy Freezing Drizzle/Freezing Rain", "type_22": "Heavy Freezing Rain", "type_23": "Heavy Rain", "type_24": "Heavy Rain And Snow", "type_25": "Heavy Snow", "type_26": "Ice", "type_27": "Light Drizzle", "type_28": "Light Drizzle/Rain", "type_29": "Light Freezing Drizzle/Freezing Rain", "type_3": "Light Freezing Rain", "type_30": "Light Rain", "type_31": "Light Rain And Snow", "type_32": "Light Snow", "type_33": "Lightning Without Thunder", "type_34": "Mist", "type_35": "Overcast", "type_36": "Partially cloudy", "type_37": "Precipitation In Vicinity", "type_38": "Rain", "type_39": "Rain Showers", "type_4": "Sky Coverage Decreasing", "type_40": "Sky Coverage Increasing", "type_41": "Sky Unchanged", "type_42": "Smoke Or Haze", "type_43": "Snow", "type_5": "Snow And Rain Showers", "type_6": "Snow Showers", "type_7": "Squalls", "type_8": "Thunderstorm", "type_9": "Thunderstorm Without Precipitation"}'

In [37]:
with open("conditions_en.json", "a") as f:
    f.write(conditions_json)